package projekt.inz.pojo;
// Generated 2017-12-21 17:34:24 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "admin", catalog = "inz"
)
public class Admin implements java.io.Serializable {

    private Integer idAdmina;
    private String login;
    private String haslo;

    public Admin() {
    }

    public Admin(String login, String haslo) {
        this.login = login;
        this.haslo = haslo;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_admina", unique = true, nullable = false)
    public Integer getIdAdmina() {
        return this.idAdmina;
    }

    public void setIdAdmina(Integer idAdmina) {
        this.idAdmina = idAdmina;
    }

    @Column(name = "login", nullable = false, length = 30)
    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    @Column(name = "haslo", nullable = false, length = 30)
    public String getHaslo() {
        return this.haslo;
    }

    public void setHaslo(String haslo) {
        this.haslo = haslo;
    }

}
