package projekt.inz.pojo;
// Generated 2018-01-05 19:10:37 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * KartaPacjenta generated by hbm2java
 */
@Entity
@Table(name="karta_pacjenta"
    ,catalog="inz"
)
public class KartaPacjenta  implements java.io.Serializable {


     private Integer idKartyPacjenta;
     private Pacjent pacjent;
     private Wizyta wizyta;
     private String historiaChoroby;

    public KartaPacjenta() {
    }

    public KartaPacjenta(Pacjent pacjent, Wizyta wizyta, String historiaChoroby) {
       this.pacjent = pacjent;
       this.wizyta = wizyta;
       this.historiaChoroby = historiaChoroby;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_karty_pacjenta", unique=true, nullable=false)
    public Integer getIdKartyPacjenta() {
        return this.idKartyPacjenta;
    }
    
    public void setIdKartyPacjenta(Integer idKartyPacjenta) {
        this.idKartyPacjenta = idKartyPacjenta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pacjenta_fk", nullable=false)
    public Pacjent getPacjent() {
        return this.pacjent;
    }
    
    public void setPacjent(Pacjent pacjent) {
        this.pacjent = pacjent;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_wyzyty_fk", nullable=false)
    public Wizyta getWizyta() {
        return this.wizyta;
    }
    
    public void setWizyta(Wizyta wizyta) {
        this.wizyta = wizyta;
    }

    
    @Column(name="historia_choroby", nullable=false, length=30)
    public String getHistoriaChoroby() {
        return this.historiaChoroby;
    }
    
    public void setHistoriaChoroby(String historiaChoroby) {
        this.historiaChoroby = historiaChoroby;
    }




}


