package projekt.inz.pojo;
// Generated 2017-11-18 19:09:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pacjent generated by hbm2java
 */
public class Pacjent  implements java.io.Serializable {


     private Integer idPacjenta;
     private String imie;
     private String nazwisko;
     private String login;
     private String haslo;
     private String email;
     private String adres;
     private String pesel;
     private String role;

    public Pacjent() {
    }

	
    public Pacjent(String imie, String nazwisko, String login, String haslo, String email, String adres, String pesel, String role) {
        this.imie = imie;
        this.nazwisko = nazwisko;
        this.login = login;
        this.haslo = haslo;
        this.email = email;
        this.adres = adres;
        this.pesel = pesel;
        this.role = role;
    }
   
    public Integer getIdPacjenta() {
        return this.idPacjenta;
    }
    
    public void setIdPacjenta(Integer idPacjenta) {
        this.idPacjenta = idPacjenta;
    }
    public String getImie() {
        return this.imie;
    }
    
    public void setImie(String imie) {
        this.imie = imie;
    }
    public String getNazwisko() {
        return this.nazwisko;
    }
    
    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getHaslo() {
        return this.haslo;
    }
    
    public void setHaslo(String haslo) {
        this.haslo = haslo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAdres() {
        return this.adres;
    }
    
    public void setAdres(String adres) {
        this.adres = adres;
    }
    public String getPesel() {
        return this.pesel;
    }
    
    public void setPesel(String pesel) {
        this.pesel = pesel;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
}


