package projekt.inz.pojo;
// Generated 2017-12-21 17:34:24 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pacjent generated by hbm2java
 */
@Entity
@Table(name = "pacjent", catalog = "inz"
)
public class Pacjent implements java.io.Serializable {

    private Integer idPacjenta;
    private String imie;
    private String nazwisko;
    private String login;
    private String haslo;
    private String email;
    private String adres;
    private String pesel;
    private Set<KartaPacjenta> kartaPacjentas = new HashSet<KartaPacjenta>(0);
    private Set<Recepta> receptas = new HashSet<Recepta>(0);
    private Set<Skrzynka> skrzynkas = new HashSet<Skrzynka>(0);
    private Set<Wizyta> wizytas = new HashSet<Wizyta>(0);

    public Pacjent() {
    }

    public Pacjent(String imie, String nazwisko, String login, String haslo, String email, String adres, String pesel) {
        this.imie = imie;
        this.nazwisko = nazwisko;
        this.login = login;
        this.haslo = haslo;
        this.email = email;
        this.adres = adres;
        this.pesel = pesel;
    }

    public Pacjent(String imie, String nazwisko, String login, String haslo, String email, String adres, String pesel, Set<KartaPacjenta> kartaPacjentas, Set<Recepta> receptas, Set<Skrzynka> skrzynkas, Set<Wizyta> wizytas) {
        this.imie = imie;
        this.nazwisko = nazwisko;
        this.login = login;
        this.haslo = haslo;
        this.email = email;
        this.adres = adres;
        this.pesel = pesel;
        this.kartaPacjentas = kartaPacjentas;
        this.receptas = receptas;
        this.skrzynkas = skrzynkas;
        this.wizytas = wizytas;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_pacjenta", unique = true, nullable = false)
    public Integer getIdPacjenta() {
        return this.idPacjenta;
    }

    public void setIdPacjenta(Integer idPacjenta) {
        this.idPacjenta = idPacjenta;
    }

    @Column(name = "imie", nullable = false, length = 30)
    public String getImie() {
        return this.imie;
    }

    public void setImie(String imie) {
        this.imie = imie;
    }

    @Column(name = "nazwisko", nullable = false, length = 30)
    public String getNazwisko() {
        return this.nazwisko;
    }

    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }

    @Column(name = "login", nullable = false, length = 30)
    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    @Column(name = "haslo", nullable = false, length = 250)
    public String getHaslo() {
        return this.haslo;
    }

    public void setHaslo(String haslo) {
        this.haslo = haslo;
    }

    @Column(name = "email", nullable = false, length = 30)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "adres", nullable = false, length = 30)
    public String getAdres() {
        return this.adres;
    }

    public void setAdres(String adres) {
        this.adres = adres;
    }

    @Column(name = "pesel", nullable = false, length = 11)
    public String getPesel() {
        return this.pesel;
    }

    public void setPesel(String pesel) {
        this.pesel = pesel;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pacjent")
    public Set<KartaPacjenta> getKartaPacjentas() {
        return this.kartaPacjentas;
    }

    public void setKartaPacjentas(Set<KartaPacjenta> kartaPacjentas) {
        this.kartaPacjentas = kartaPacjentas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pacjent")
    public Set<Recepta> getReceptas() {
        return this.receptas;
    }

    public void setReceptas(Set<Recepta> receptas) {
        this.receptas = receptas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pacjent")
    public Set<Skrzynka> getSkrzynkas() {
        return this.skrzynkas;
    }

    public void setSkrzynkas(Set<Skrzynka> skrzynkas) {
        this.skrzynkas = skrzynkas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pacjent")
    public Set<Wizyta> getWizytas() {
        return this.wizytas;
    }

    public void setWizytas(Set<Wizyta> wizytas) {
        this.wizytas = wizytas;
    }

}
