package projekt.inz.pojo;
// Generated 2017-11-18 19:09:28 by Hibernate Tools 4.3.1



/**
 * Rejestracja generated by hbm2java
 */
public class Rejestracja  implements java.io.Serializable {


     private Integer idRejestracji;
     private Wizyta wizyta;
     private String imie;
     private String nazwisko;
     private String login;
     private String haslo;
     private String role;

    public Rejestracja() {
    }

    public Rejestracja(Wizyta wizyta, String imie, String nazwisko, String login, String haslo, String role) {
       this.wizyta = wizyta;
       this.imie = imie;
       this.nazwisko = nazwisko;
       this.login = login;
       this.haslo = haslo;
       this.role = role;
    }
   
    public Integer getIdRejestracji() {
        return this.idRejestracji;
    }
    
    public void setIdRejestracji(Integer idRejestracji) {
        this.idRejestracji = idRejestracji;
    }
    public Wizyta getWizyta() {
        return this.wizyta;
    }
    
    public void setWizyta(Wizyta wizyta) {
        this.wizyta = wizyta;
    }
    public String getImie() {
        return this.imie;
    }
    
    public void setImie(String imie) {
        this.imie = imie;
    }
    public String getNazwisko() {
        return this.nazwisko;
    }
    
    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getHaslo() {
        return this.haslo;
    }
    
    public void setHaslo(String haslo) {
        this.haslo = haslo;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
}


