package projekt.inz.pojo;
// Generated 2017-12-05 17:08:29 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Skrzynka generated by hbm2java
 */
@Entity
@Table(name="skrzynka"
    ,catalog="inz"
)
public class Skrzynka  implements java.io.Serializable {


     private Integer idWiadomosci;
     private int idNadawcy;
     private int idOdbiorcy;
     private String opis;

    public Skrzynka() {
    }

    public Skrzynka(int idNadawcy, int idOdbiorcy, String opis) {
       this.idNadawcy = idNadawcy;
       this.idOdbiorcy = idOdbiorcy;
       this.opis = opis;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_wiadomosci", unique=true, nullable=false)
    public Integer getIdWiadomosci() {
        return this.idWiadomosci;
    }
    
    public void setIdWiadomosci(Integer idWiadomosci) {
        this.idWiadomosci = idWiadomosci;
    }

    
    @Column(name="id_nadawcy", nullable=false)
    public int getIdNadawcy() {
        return this.idNadawcy;
    }
    
    public void setIdNadawcy(int idNadawcy) {
        this.idNadawcy = idNadawcy;
    }

    
    @Column(name="id_odbiorcy", nullable=false)
    public int getIdOdbiorcy() {
        return this.idOdbiorcy;
    }
    
    public void setIdOdbiorcy(int idOdbiorcy) {
        this.idOdbiorcy = idOdbiorcy;
    }

    
    @Column(name="opis", nullable=false, length=30)
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }




}


