package projekt.inz.pojo;
// Generated 2017-11-18 19:09:28 by Hibernate Tools 4.3.1



/**
 * Skrzynka generated by hbm2java
 */
public class Skrzynka  implements java.io.Serializable {


     private Integer idWiadomosci;
     private int idNadawcy;
     private int idOdbiorcy;
     private String opis;

    public Skrzynka() {
    }

    public Skrzynka(int idNadawcy, int idOdbiorcy, String opis) {
       this.idNadawcy = idNadawcy;
       this.idOdbiorcy = idOdbiorcy;
       this.opis = opis;
    }
   
    public Integer getIdWiadomosci() {
        return this.idWiadomosci;
    }
    
    public void setIdWiadomosci(Integer idWiadomosci) {
        this.idWiadomosci = idWiadomosci;
    }
    public int getIdNadawcy() {
        return this.idNadawcy;
    }
    
    public void setIdNadawcy(int idNadawcy) {
        this.idNadawcy = idNadawcy;
    }
    public int getIdOdbiorcy() {
        return this.idOdbiorcy;
    }
    
    public void setIdOdbiorcy(int idOdbiorcy) {
        this.idOdbiorcy = idOdbiorcy;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }
}


