package projekt.inz.pojo;
// Generated 2017-12-05 17:08:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Uslugi generated by hbm2java
 */
@Entity
@Table(name="uslugi"
    ,catalog="inz"
)
public class Uslugi  implements java.io.Serializable {


     private Integer idUslugi;
     private String opis;
     private int cena;
     private Set wizytas = new HashSet(0);

    public Uslugi() {
    }

	
    public Uslugi(String opis, int cena) {
        this.opis = opis;
        this.cena = cena;
    }
    public Uslugi(String opis, int cena, Set wizytas) {
       this.opis = opis;
       this.cena = cena;
       this.wizytas = wizytas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_uslugi", unique=true, nullable=false)
    public Integer getIdUslugi() {
        return this.idUslugi;
    }
    
    public void setIdUslugi(Integer idUslugi) {
        this.idUslugi = idUslugi;
    }

    
    @Column(name="opis", nullable=false, length=30)
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }

    
    @Column(name="cena", nullable=false)
    public int getCena() {
        return this.cena;
    }
    
    public void setCena(int cena) {
        this.cena = cena;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="uslugi")
    public Set getWizytas() {
        return this.wizytas;
    }
    
    public void setWizytas(Set wizytas) {
        this.wizytas = wizytas;
    }




}


