package projekt.inz.pojo;
// Generated 2017-11-18 19:09:28 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Wizyta generated by hbm2java
 */
public class Wizyta  implements java.io.Serializable {


     private Integer idWizyty;
     private Doktor doktor;
     private Pacjent pacjent;
     private Date terminWizyty;
     private String uwagi;
     

    public Wizyta() {
    }

	
    public Wizyta(Date terminWizyty, String uwagi) {
        this.terminWizyty = terminWizyty;
        this.uwagi = uwagi;
    }
    public Wizyta(Doktor doktor, Pacjent pacjent, Date terminWizyty, String uwagi) {
       this.doktor = doktor;
       this.pacjent = pacjent;
       this.terminWizyty = terminWizyty;
       this.uwagi = uwagi;
    }
   
    public Integer getIdWizyty() {
        return this.idWizyty;
    }
    
    public void setIdWizyty(Integer idWizyty) {
        this.idWizyty = idWizyty;
    }
    public Doktor getDoktor() {
        return this.doktor;
    }
    
    public void setDoktor(Doktor doktor) {
        this.doktor = doktor;
    }
    public Pacjent getPacjent() {
        return this.pacjent;
    }
    
    public void setPacjent(Pacjent pacjent) {
        this.pacjent = pacjent;
    }
    public Date getTerminWizyty() {
        return this.terminWizyty;
    }
    
    public void setTerminWizyty(Date terminWizyty) {
        this.terminWizyty = terminWizyty;
    }
    public String getUwagi() {
        return this.uwagi;
    }
    
    public void setUwagi(String uwagi) {
        this.uwagi = uwagi;
    }
}


