package projekt.inz.pojo;
// Generated 2017-12-21 17:34:24 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Wizyta generated by hbm2java
 */
@Entity
@Table(name = "wizyta", catalog = "inz"
)
public class Wizyta implements java.io.Serializable {

    private Integer idWizyty;
    private Doktor doktor;
    private Pacjent pacjent;
    private Uslugi uslugi;
    private Date terminWizyty;
    private Set<Rejestracja> rejestracjas = new HashSet<Rejestracja>(0);
    private Set<KartaPacjenta> kartaPacjentas = new HashSet<KartaPacjenta>(0);

    public Wizyta() {
    }

    public Wizyta(Doktor doktor, Pacjent pacjent, Uslugi uslugi, Date terminWizyty) {
        this.doktor = doktor;
        this.pacjent = pacjent;
        this.uslugi = uslugi;
        this.terminWizyty = terminWizyty;
    }

    public Wizyta(Doktor doktor, Pacjent pacjent, Uslugi uslugi, Date terminWizyty, Set<Rejestracja> rejestracjas, Set<KartaPacjenta> kartaPacjentas) {
        this.doktor = doktor;
        this.pacjent = pacjent;
        this.uslugi = uslugi;
        this.terminWizyty = terminWizyty;
        this.rejestracjas = rejestracjas;
        this.kartaPacjentas = kartaPacjentas;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_wizyty", unique = true, nullable = false)
    public Integer getIdWizyty() {
        return this.idWizyty;
    }

    public void setIdWizyty(Integer idWizyty) {
        this.idWizyty = idWizyty;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_doktora_fk", nullable = false)
    public Doktor getDoktor() {
        return this.doktor;
    }

    public void setDoktor(Doktor doktor) {
        this.doktor = doktor;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_pacjenta_fk", nullable = false)
    public Pacjent getPacjent() {
        return this.pacjent;
    }

    public void setPacjent(Pacjent pacjent) {
        this.pacjent = pacjent;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_uslugi_fk", nullable = false)
    public Uslugi getUslugi() {
        return this.uslugi;
    }

    public void setUslugi(Uslugi uslugi) {
        this.uslugi = uslugi;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "termin_wizyty", nullable = false, length = 19)
    public Date getTerminWizyty() {
        return this.terminWizyty;
    }

    public void setTerminWizyty(Date terminWizyty) {
        this.terminWizyty = terminWizyty;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "wizyta")
    public Set<Rejestracja> getRejestracjas() {
        return this.rejestracjas;
    }

    public void setRejestracjas(Set<Rejestracja> rejestracjas) {
        this.rejestracjas = rejestracjas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "wizyta")
    public Set<KartaPacjenta> getKartaPacjentas() {
        return this.kartaPacjentas;
    }

    public void setKartaPacjentas(Set<KartaPacjenta> kartaPacjentas) {
        this.kartaPacjentas = kartaPacjentas;
    }

}
